services:
  - type: web
    name: jobspy-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python minimal_app.py
    envVars:
      - key: PORT
        value: 8000
